In [21]:
#From Mark Newman's book Computational Physics

from numpy import array,empty

A = array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]], float)
v = array([ -4, 3, 9, 7 ],float)
N = len(v)

# Gaussian elimination
for m in range(N):

    # Divide by the diagonal element
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div

    # Now subtract from the lower rows
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# Backsubstitution
x = empty(N,float)
for m in range(N-1,-1,-1):
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]

print(x)

[ 2. -1. -2.  1.]


In [2]:
def gauss_elim(A,v):
    N = len(v)

# Gaussian elimination
    for m in range(N):

    # Divide by the diagonal element
        div = A[m,m]
        A[m,:] /= div
        v[m] /= div

    # Now subtract from the lower rows
        for i in range(m+1,N):
            mult = A[i,m]
            A[i,:] -= mult*A[m,:]
            v[i] -= mult*v[m]

# Backsubstitution
    x = empty(N,float)
    for m in range(N-1,-1,-1):
        x[m] = v[m]
        for i in range(m+1,N):
            x[m] -= A[m,i]*x[i]

    print(x)

In [23]:
A = array([[ 1,  1,  -2,  1, 3, -1 ],
           [ 2, -1, 1, 2, 1, -3 ],
           [ 1, 3, -3, -1, 2, 1 ],
           [ 5, 2, -1, -1, 2, 1 ],
           [ -3, -1, 2, 3, 1, 3 ],
           [ 4, 3,  1,  -6, -3, -2 ]], float)
v = array([ 4, 20, -15, -3, 16, -27 ],float)
gauss_elim(A,v)

[ 1. -2.  3.  4.  2. -1.]


In [12]:
from numpy.linalg import solve
from numpy import allclose,dot

In [24]:
solve(A,v)

array([ 1., -2.,  3.,  4.,  2., -1.])

In [13]:
x=solve(A,v)

In [15]:
allclose(dot(A,x),v)

True

In [16]:
help(allclose)

Help on function allclose in module numpy.core.numeric:

allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns True if two arrays are element-wise equal within a tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    If either array contains one or more NaNs, False is returned.
    Infs are treated as equal if they are in the same place and of the same
    sign in both arrays.
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : float
        The relative tolerance parameter (see Notes).
    atol : float
        The absolute tolerance parameter (see Notes).
    equal_nan : bool
        Whether to compare NaN's as equal.  If True, NaN's in `a` will be
        considered equal to NaN's in `b` in the output array.
   

In [18]:
from numpy.linalg import eigh

In [29]:
A=array([[0,.5],[-.5,0]])
print(A)

[[ 0.   0.5]
 [-0.5  0. ]]


In [30]:
eigh(A)

(array([-0.5,  0.5]), array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [28]:
help(eigh)

Help on function eigh in module numpy.linalg.linalg:

eigh(a, UPLO='L')
    Return the eigenvalues and eigenvectors of a Hermitian or symmetric matrix.
    
    Returns two objects, a 1-D array containing the eigenvalues of `a`, and
    a 2-D square array or matrix (depending on the input type) of the
    corresponding eigenvectors (in columns).
    
    Parameters
    ----------
    a : (..., M, M) array
        Hermitian/Symmetric matrices whose eigenvalues and
        eigenvectors are to be computed.
    UPLO : {'L', 'U'}, optional
        Specifies whether the calculation is done with the lower triangular
        part of `a` ('L', default) or the upper triangular part ('U').
        Irrespective of this value only the real parts of the diagonal will
        be considered in the computation to preserve the notion of a Hermitian
        matrix. It therefore follows that the imaginary part of the diagonal
        will always be treated as zero.
    
    Returns
    -------
    w : (..